linux_mbedtls_v3_task: # use master branch of libevent to support mbedtls
    container:
      matrix:
          - image: ubuntu:24.04

    install_script:
        - apt update && apt upgrade -y
        - DEBIAN_FRONTEND=noninteractive apt install -y unzip git cmake build-essential curl libssl-dev libmbedtls-dev libevent-dev libevent-pthreads-2.1-7t64 libevent-openssl-2.1-7t64 libevent-2.1-7t64 libevent-core-2.1-7t64 libevent-extra-2.1-7t64 libpcre3-dev python3-dev
    prepare_script:
        - git submodule update --init
        - curl -L https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v3.5.2.zip -o mbedtls.zip
        - unzip mbedtls.zip
        - cd mbedtls-3.5.2 && cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=OFF -DENABLE_PROGRAMS=OFF . && make install && cd ..
    build_default_test_script:
        - mkdir -p build/default
        - cd build/default
        - cmake -DUSE_MBEDTLS=ON ../..
        - make
        - make test
    build_acl_test_script:
        - mkdir -p build/acl
        - cd build/acl
        - cmake -DUSE_MBEDTLS=ON -DWITH_ACL=ON ../..
        - make
        - make test

linux_mbedtls_v2_task: # use master branch of libevent to support mbedtls
    container:
      matrix:
          - image: ubuntu:24.04

    install_script:
        - apt update && apt upgrade -y
        - DEBIAN_FRONTEND=noninteractive apt install -y unzip git cmake build-essential curl libssl-dev libmbedtls-dev libevent-dev libevent-pthreads-2.1-7t64 libevent-openssl-2.1-7t64 libevent-2.1-7t64 libevent-core-2.1-7t64 libevent-extra-2.1-7t64 libpcre3-dev python3-dev
    prepare_script:
        - git submodule update --init
        - curl -L https://github.com/ARMmbed/mbedtls/archive/refs/tags/v2.27.0.zip -o mbedtls.zip
        - unzip mbedtls.zip
        - cd mbedtls-2.27.0 && cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=OFF -DENABLE_PROGRAMS=OFF . && make install && cd ..
    build_default_test_script:
        - mkdir -p build/default
        - cd build/default
        - cmake -DUSE_MBEDTLS=ON ../..
        - make
        - make test
    build_acl_test_script:
        - mkdir -p build/acl
        - cd build/acl
        - cmake -DUSE_MBEDTLS=ON -DWITH_ACL=ON ../..
        - make
        - make test
